// Generated by CoffeeScript 1.3.1
(function() {

  $(window).load(function() {
    var dlog, img, _DEBUG_;
    console.log('HI');
    _DEBUG_ = true;
    dlog = function(msg) {
      if (_DEBUG_) {
        return console.log(msg);
      }
    };
    img = $('#testimage')[0];
    window.img = img;
    $(img).on('canvasready', function(e, c) {
      return Franz.resize(c, 400, 300, 200, 100, function(c) {
        c.id = 'resizedcanvas';
        return $('#resize_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.scale(c, 0.1, function(c) {
        c.id = 'scaledcanvas';
        return $('#scale_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.crop(c, 580, 330, 100, 100, function(c) {
        c.id = 'cropedcanvas';
        return $('#crop_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.invert(c, function(c) {
        return $('#invert_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.mosaic(c, 8, function(c) {
        return $('#mosaic_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.binarize(c, 0.5, function(c) {
        return $('#binarize_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.noise(c, 90, function(c) {
        return $('#noise_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.vignette(c, 0.2, 0.8, function(c) {
        return $('#vignette_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.saturate(c, 0.2, function(c) {
        return $('#saturate_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.desaturate(c, 0.4, function(c) {
        return $('#desaturate_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.curve(c, function(c) {
        return $('#curve_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.screen(c, 227, 12, 169, 0.9, function(c) {
        return $('#screen_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.viewfinder(c, null, function(c) {
        return $('#viewfinder_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.oldschool(c, null, function(c) {
        return $('#oldschool_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      var actions, params;
      actions = [Franz.curve, Franz.scale, Franz.screen, Franz.saturate, Franz.vignette, Franz.oldschool, Franz.toImage];
      params = [[], 0.8, [227, 12, 169, 0.40], 0.9, [0.2, 0.8], ['./img/oldschool.png'], []];
      return Franz.many(c, actions, params, function(c) {
        return $('#many_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      var oilbutton;
      oilbutton = $('<button>Click Me!</button>').on('click', function() {
        return Franz.oil(c, 4, 30, function(c) {
          return $('#oil_placeholder').html(c);
        });
      });
      return $('#oil_placeholder').html(oilbutton);
    });
    $(img).on('canvasready', function(e, c) {
      var button;
      button = $('<button>Click Me!</button>').on('click', function() {
        return Franz.removeNoise(c, function(c) {
          return $('#removenoise_placeholder').html(c);
        });
      });
      return $('#removenoise_placeholder').html(button);
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.schemer(c, [127, 255], [127, 255], [127, 255], [], [0, 255], [0, 255], [0, 255], [], function(c) {
        return $('#schemer_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.reduceAndReplace(c, [[0, 0, 0], [255, 255, 255], [255, 0, 0], [0, 255, 0], [0, 0, 255]], function(c) {
        return $('#reduceandreplace_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.c64(c, function(c) {
        return $('#c64_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.applyIfRgba(c, Franz.blackWhite, [], (function(r, g, b, a, i) {
        if (r > g || b > g) {
          return true;
        } else {
          return false;
        }
      }), function(c) {
        return $('#applyifrgba_placeholder').html(c);
      });
    });
    $(img).on('canvasready', function(e, c) {
      return Franz.preserveYellow(c, 127, 127, 60, function(c) {
        return $('#preserveyellow_placeholder').html(c);
      });
    });
    return Franz.byImage(img, function(c) {
      $('#byImage_placeholder').html(c);
      c.id = 'canvasbyimage';
      return $(img).trigger('canvasready', c);
    });
  });

}).call(this);
