// Generated by CoffeeScript 1.3.1
(function() {

  Franz.binarize = mF(ImageFilters.Binarize, 0.5);

  Franz.boxBlur = mF(ImageFilters.BoxBlur, 3, 3, 2);

  Franz.gaussianBlur = mF(ImageFilters.GaussianBlur, 2);

  Franz.stackBlur = mF(ImageFilters.StackBlur, 6);

  Franz.brightness = mF(ImageFilters.brightness, 1);

  Franz.brightnessConstrastGimp = mF(ImageFilters.BrightnessContrastGimp, 50, 50);

  Franz.brightnessConstrastPhotoshop = mF(ImageFilters.BrightnessContrastPhotoshop, 50, 50);

  Franz.Channels = function(channel_string) {
    var channel;
    if (channel_string === "blue" || channel_string === "b") {
      channel = 3;
    } else if (channel_string === "green" || channel_string === "g") {
      channel = 2;
    } else {
      channel = channel_string;
    }
    return mF(ImageFilters.Channels, channel);
  };

  Franz.colorTransform = mF(ImageFilters.ColorTransformFilter, 1, 1, 1, 0, 0, 0);

  Franz.dither = mF(ImageFilters.Dither, 2);

  Franz.edge = mF(ImageFilters.Edge);

  Franz.emboss = mF(ImageFilters.Emboss);

  Franz.enrich = mF(ImageFilters.Enrich);

  Franz.gamma = mF(ImageFilters.Gamma, 2);

  Franz.HSLAdjustment = mF(ImageFilters.HSLAdjustment, 0, 0, 0);

  Franz.invert = mF(ImageFilters.Invert);

  Franz.mosaic = mF(ImageFilters.Mosaic, 10);

  Franz.oil = mF(ImageFilters.Oil, 4, 30);

  Franz.sharpen = mF(ImageFilters.Sharpen, 3);

  Franz.twirl = mF(ImageFilters.Twril, 0.5, 0.5, 100, 360);

}).call(this);
