// Generated by CoffeeScript 1.3.1
(function() {
  var crop, hardResize, resize, scale,
    __slice = [].slice;

  Franz.hardResize = hardResize = function(c, w, h, cb) {
    var new_c, new_ctx, _ref;
    _ref = Franz.newToolbox(w, h), new_c = _ref[0], new_ctx = _ref[1];
    new_ctx.drawImage(c, 0, 0, w, h);
    return nb(cb, new_c);
  };

  Franz.resize = resize = function() {
    var c, cb, first, max, min, new_c, new_ctx, p, r, second, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    max = {
      width: null,
      height: null
    };
    min = {
      width: null,
      height: null
    };
    _ref = fff(p, 800, null, null, null, null, null), cb = _ref[0], max['width'] = _ref[1], max['height'] = _ref[2], min['width'] = _ref[3], min['height'] = _ref[4], first = _ref[5];
    second = null;
    r = {
      width: null,
      height: null
    };
    if (first === 'width') {
      second = 'height';
    } else if (first === 'height') {
      second = 'width';
    } else {
      if (c.height > c.width) {
        first = 'height';
        second = 'width';
      } else {
        first = 'width';
        second = 'height';
      }
    }
    console.log('hallo');
    if (max[first] && (c[first] > max[first] || c[second] > max[second])) {
      r[second] = c[second] * max[first] / c[first];
      r[first] = max[first];
      if (r[second] > max[second]) {
        r[first] = c[first] * max[second] / c[second];
        r[second] = max[second];
      }
    } else if (min[first] && (c[first] < min[first] || c[second] > min[second])) {
      r[first] = c[first] * min[second] / c[second];
      r[second] = min[second];
      if (r[first] < min[first]) {
        r[second] = c[second] * min[first] / c[first];
        r[first] = min[first];
      }
    } else {
      r[first] = c[first];
      r[second] = c[second];
    }
    _ref1 = newToolbox(r.width, r.height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, 0, 0, r.width, r.height);
    return nb(cb, new_c);
  };

  Franz.scale = scale = function() {
    var c, cb, new_c, new_ctx, new_height, new_width, p, x, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 1), cb = _ref[0], x = _ref[1];
    new_width = c.width * x;
    new_height = c.height * x;
    _ref1 = newToolbox(new_width, new_height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, 0, 0, new_width, new_height);
    return nb(cb, new_c);
  };

  Franz.crop = crop = function() {
    var c, cb, crop_height, crop_width, crop_x, crop_y, new_c, new_ctx, p, _ref, _ref1;
    c = arguments[0], p = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _ref = fff(p, 0, 0, c.width / 2, c.height / 2), cb = _ref[0], crop_x = _ref[1], crop_y = _ref[2], crop_width = _ref[3], crop_height = _ref[4];
    _ref1 = newToolbox(crop_width, crop_height, (c != null ? c.getAttribute('id') : void 0) || (c != null ? c.getAttribute('origin') : void 0)), new_c = _ref1[0], new_ctx = _ref1[1];
    new_ctx.drawImage(c, crop_x, crop_y, crop_width, crop_height, 0, 0, crop_width, crop_height);
    return nb(cb, new_c);
  };

}).call(this);
